version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
      - CORS_ORIGIN=http://localhost:4200
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge