version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
      - CORS_ORIGIN=http://frontend
    volumes:
      - backend_data:/app/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:3000
      - FRONTEND_URL=http://frontend
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ./tests/reports:/tests/reports

volumes:
  backend_data:
    driver: local

networks:
  test-network:
    driver: bridge